# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 5875bae
_src_path: gh:canonical/platform-engineering-documentation-files.git
author: Canonical Ltd.
discourse: https://discourse.charmhub.io
display_contributors: false
docs_host: canonical.com
github_url: https://github.com/canonical/github-runner-operators
html_favicon: ''
license_name: Apache-2.0
license_url: https://github.com/canonical/github-runner-operators/blob/main/LICENSE
linkcheck_timeout: 30
llms_txt_description: This is the documentation for the GitHub runner charms, a collection
    of Juju charms deploying and managing self-hosted GitHub runners.
matrix: https://matrix.to/#/#charmhub-charmdev:ubuntu.com
mattermost: ''
new_domain: canonical.com/juju/docs/github-runner-charms
ogp_image: https://assets.ubuntu.com/v1/cc828679-docs_illustration.svg
old_domain: canonical-github-runner-charms.readthedocs-hosted.com
product_page: github.com/canonical/github-runner-operators
product_tag: ''
project: GitHub runner operators
repo_default_branch: main
repo_folder: /docs/
rtd_slug: juju/docs/github-runner-charms
source_edit_link: https://github.com/canonical/github-runner-operators
