# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ControllerInfo(BaseModel):
    """
    ControllerInfo
    """ # noqa: E501
    agent_url: Optional[StrictStr] = Field(default=None, description="AgentURL is the URL where the GARM agent will connect. If set behind a reverse proxy, this URL must be configured to allow websocket connections.")
    ca_cert_bundle: Optional[List[StrictInt]] = Field(default=None, description="CACertBundle holds a certificate bundle meant to validate the certificate used by GARM itself. This can be just the root certificate that can validate the GARM TLS certificate, a chain or multiple root CAs.")
    cached_garm_agent_release_fetched_at: Optional[datetime] = Field(default=None, description="CachedGARMAgentReleaseFetchedAt is the timestamp when the release data was last fetched from GARMAgentReleasesURL")
    callback_url: Optional[StrictStr] = Field(default=None, description="CallbackURL is the URL where instances can send updates back to the controller. This URL is used by instances to send status updates back to the controller. The URL itself may be made available to instances via a reverse proxy or a load balancer. That means that the user is responsible for telling GARM what the public URL is, by setting this field.")
    controller_id: Optional[UUID] = Field(default=None, description="ControllerID is the unique ID of this controller. This ID gets generated automatically on controller init.")
    controller_webhook_url: Optional[StrictStr] = Field(default=None, description="ControllerWebhookURL is the controller specific URL where webhooks will be received. This field holds the WebhookURL defined above to which we append the ControllerID. Functionally it is the same as WebhookURL, but it allows us to safely manage webhooks from GARM without accidentally removing webhooks from other services or GARM controllers.")
    enable_agent_tools_sync: Optional[StrictBool] = Field(default=None, description="SyncGARMAgentTools enables or disables automatic sync of garm-agent tools.")
    garm_agent_releases_url: Optional[StrictStr] = Field(default=None, description="GARMAgentReleasesURL is the URL from where GARM can fetch garm-agent binaries. This URL must have an API response compatible with the github releases API. The default value for this field is: https://api.github.com/repos/cloudbase/garm-agent/releases")
    hostname: Optional[StrictStr] = Field(default=None, description="Hostname is the hostname of the machine that runs this controller. In the future, this field will be migrated to a separate table that will keep track of each the controller nodes that are part of a cluster. This will happen when we implement controller scale-out capability.")
    metadata_url: Optional[StrictStr] = Field(default=None, description="MetadataURL is the public metadata URL of the GARM instance. This URL is used by instances to fetch information they need to set themselves up. The URL itself may be made available to runners via a reverse proxy or a load balancer. That means that the user is responsible for telling GARM what the public URL is, by setting this field.")
    minimum_job_age_backoff: Optional[StrictInt] = Field(default=None, description="MinimumJobAgeBackoff is the minimum time in seconds that a job must be in queued state before GARM will attempt to allocate a runner for it. When set to a non zero value, GARM will ignore the job until the job's age is greater than this value. When using the min_idle_runners feature of a pool, this gives enough time for potential idle runners to pick up the job before GARM attempts to allocate a new runner, thus avoiding the need to potentially scale down runners later.")
    version: Optional[StrictStr] = Field(default=None, description="Version is the version of the GARM controller.")
    webhook_url: Optional[StrictStr] = Field(default=None, description="WebhookURL is the base URL where the controller will receive webhooks from github. When webhook management is used, this URL is used as a base to which the controller UUID is appended and which will receive the webhooks. The URL itself may be made available to instances via a reverse proxy or a load balancer. That means that the user is responsible for telling GARM what the public URL is, by setting this field.")
    __properties: ClassVar[List[str]] = ["agent_url", "ca_cert_bundle", "cached_garm_agent_release_fetched_at", "callback_url", "controller_id", "controller_webhook_url", "enable_agent_tools_sync", "garm_agent_releases_url", "hostname", "metadata_url", "minimum_job_age_backoff", "version", "webhook_url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ControllerInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ControllerInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_url": obj.get("agent_url"),
            "ca_cert_bundle": obj.get("ca_cert_bundle"),
            "cached_garm_agent_release_fetched_at": obj.get("cached_garm_agent_release_fetched_at"),
            "callback_url": obj.get("callback_url"),
            "controller_id": obj.get("controller_id"),
            "controller_webhook_url": obj.get("controller_webhook_url"),
            "enable_agent_tools_sync": obj.get("enable_agent_tools_sync"),
            "garm_agent_releases_url": obj.get("garm_agent_releases_url"),
            "hostname": obj.get("hostname"),
            "metadata_url": obj.get("metadata_url"),
            "minimum_job_age_backoff": obj.get("minimum_job_age_backoff"),
            "version": obj.get("version"),
            "webhook_url": obj.get("webhook_url")
        })
        return _obj


