# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateRepoParams(BaseModel):
    """
    CreateRepoParams
    """ # noqa: E501
    agent_mode: Optional[StrictBool] = None
    credentials_name: Optional[StrictStr] = None
    forge_type: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    owner: Optional[StrictStr] = None
    pool_balancer_type: Optional[StrictStr] = None
    webhook_secret: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["agent_mode", "credentials_name", "forge_type", "name", "owner", "pool_balancer_type", "webhook_secret"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateRepoParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateRepoParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_mode": obj.get("agent_mode"),
            "credentials_name": obj.get("credentials_name"),
            "forge_type": obj.get("forge_type"),
            "name": obj.get("name"),
            "owner": obj.get("owner"),
            "pool_balancer_type": obj.get("pool_balancer_type"),
            "webhook_secret": obj.get("webhook_secret")
        })
        return _obj


