# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreatePoolParams(BaseModel):
    """
    CreatePoolParams
    """ # noqa: E501
    enable_shell: Optional[StrictBool] = None
    enabled: Optional[StrictBool] = None
    extra_specs: Optional[Dict[str, Any]] = None
    flavor: Optional[StrictStr] = None
    github_runner_group: Optional[StrictStr] = Field(default=None, description="GithubRunnerGroup is the github runner group in which the runners of this pool will be added to. The runner group must be created by someone with access to the enterprise.", alias="github-runner-group")
    image: Optional[StrictStr] = None
    max_runners: Optional[StrictInt] = None
    min_idle_runners: Optional[StrictInt] = None
    os_arch: Optional[StrictStr] = None
    os_type: Optional[StrictStr] = None
    priority: Optional[StrictInt] = None
    provider_name: Optional[StrictStr] = None
    runner_bootstrap_timeout: Optional[StrictInt] = None
    runner_prefix: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    template_id: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["enable_shell", "enabled", "extra_specs", "flavor", "github-runner-group", "image", "max_runners", "min_idle_runners", "os_arch", "os_type", "priority", "provider_name", "runner_bootstrap_timeout", "runner_prefix", "tags", "template_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatePoolParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatePoolParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enable_shell": obj.get("enable_shell"),
            "enabled": obj.get("enabled"),
            "extra_specs": obj.get("extra_specs"),
            "flavor": obj.get("flavor"),
            "github-runner-group": obj.get("github-runner-group"),
            "image": obj.get("image"),
            "max_runners": obj.get("max_runners"),
            "min_idle_runners": obj.get("min_idle_runners"),
            "os_arch": obj.get("os_arch"),
            "os_type": obj.get("os_type"),
            "priority": obj.get("priority"),
            "provider_name": obj.get("provider_name"),
            "runner_bootstrap_timeout": obj.get("runner_bootstrap_timeout"),
            "runner_prefix": obj.get("runner_prefix"),
            "tags": obj.get("tags"),
            "template_id": obj.get("template_id")
        })
        return _obj


