# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from garm_client.models.forge_endpoint import ForgeEndpoint
from garm_client.models.github_rate_limit import GithubRateLimit
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ForgeCredentials(BaseModel):
    """
    ForgeCredentials
    """ # noqa: E501
    api_base_url: Optional[StrictStr] = None
    auth_type: Optional[StrictStr] = Field(default=None, alias="auth-type")
    base_url: Optional[StrictStr] = None
    ca_bundle: Optional[Union[Annotated[bytes, Field(strict=True)], Annotated[str, Field(strict=True)]]] = None
    created_at: Optional[datetime] = None
    description: Optional[StrictStr] = None
    endpoint: Optional[ForgeEndpoint] = None
    enterprises: Optional[List[Enterprise]] = None
    forge_type: Optional[StrictStr] = None
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    organizations: Optional[List[Organization]] = None
    rate_limit: Optional[GithubRateLimit] = None
    repositories: Optional[List[Repository]] = None
    updated_at: Optional[datetime] = None
    upload_base_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["api_base_url", "auth-type", "base_url", "ca_bundle", "created_at", "description", "endpoint", "enterprises", "forge_type", "id", "name", "organizations", "rate_limit", "repositories", "updated_at", "upload_base_url"]

    @field_validator('ca_bundle')
    def ca_bundle_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$", value):
            raise ValueError(r"must validate the regular expression /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ForgeCredentials from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of endpoint
        if self.endpoint:
            _dict['endpoint'] = self.endpoint.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in enterprises (list)
        _items = []
        if self.enterprises:
            for _item_enterprises in self.enterprises:
                if _item_enterprises:
                    _items.append(_item_enterprises.to_dict())
            _dict['enterprises'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in organizations (list)
        _items = []
        if self.organizations:
            for _item_organizations in self.organizations:
                if _item_organizations:
                    _items.append(_item_organizations.to_dict())
            _dict['organizations'] = _items
        # override the default output from pydantic by calling `to_dict()` of rate_limit
        if self.rate_limit:
            _dict['rate_limit'] = self.rate_limit.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in repositories (list)
        _items = []
        if self.repositories:
            for _item_repositories in self.repositories:
                if _item_repositories:
                    _items.append(_item_repositories.to_dict())
            _dict['repositories'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ForgeCredentials from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_base_url": obj.get("api_base_url"),
            "auth-type": obj.get("auth-type"),
            "base_url": obj.get("base_url"),
            "ca_bundle": obj.get("ca_bundle"),
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "endpoint": ForgeEndpoint.from_dict(obj["endpoint"]) if obj.get("endpoint") is not None else None,
            "enterprises": [Enterprise.from_dict(_item) for _item in obj["enterprises"]] if obj.get("enterprises") is not None else None,
            "forge_type": obj.get("forge_type"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "organizations": [Organization.from_dict(_item) for _item in obj["organizations"]] if obj.get("organizations") is not None else None,
            "rate_limit": GithubRateLimit.from_dict(obj["rate_limit"]) if obj.get("rate_limit") is not None else None,
            "repositories": [Repository.from_dict(_item) for _item in obj["repositories"]] if obj.get("repositories") is not None else None,
            "updated_at": obj.get("updated_at"),
            "upload_base_url": obj.get("upload_base_url")
        })
        return _obj

from garm_client.models.enterprise import Enterprise
from garm_client.models.organization import Organization
from garm_client.models.repository import Repository
# TODO: Rewrite to not use raise_errors
ForgeCredentials.model_rebuild(raise_errors=False)

