# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from garm_client.models.garm_agent_tools_paginated_response_results_inner import GARMAgentToolsPaginatedResponseResultsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GARMAgentToolsPaginatedResponse(BaseModel):
    """
    GARMAgentToolsPaginatedResponse
    """ # noqa: E501
    current_page: Optional[StrictInt] = None
    next_page: Optional[StrictInt] = None
    pages: Optional[StrictInt] = None
    previous_page: Optional[StrictInt] = None
    results: Optional[List[GARMAgentToolsPaginatedResponseResultsInner]] = None
    total_count: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["current_page", "next_page", "pages", "previous_page", "results", "total_count"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GARMAgentToolsPaginatedResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in results (list)
        _items = []
        if self.results:
            for _item_results in self.results:
                if _item_results:
                    _items.append(_item_results.to_dict())
            _dict['results'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GARMAgentToolsPaginatedResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "current_page": obj.get("current_page"),
            "next_page": obj.get("next_page"),
            "pages": obj.get("pages"),
            "previous_page": obj.get("previous_page"),
            "results": [GARMAgentToolsPaginatedResponseResultsInner.from_dict(_item) for _item in obj["results"]] if obj.get("results") is not None else None,
            "total_count": obj.get("total_count")
        })
        return _obj


