# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from garm_client.models.garm_agent_release_asset import GARMAgentReleaseAsset
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GARMAgentRelease(BaseModel):
    """
    GARMAgentRelease describes one garm-agent release available at the controller's releases URL, as recorded in the cached release index.
    """ # noqa: E501
    assets: Optional[List[GARMAgentReleaseAsset]] = Field(default=None, description="Assets lists the downloadable binaries the release ships. Checksum files are omitted; the digest of each asset is included instead.")
    latest: Optional[StrictBool] = Field(default=None, description="Latest indicates this is the release \"latest\" currently resolves to.")
    os_archs: Optional[List[StrictStr]] = Field(default=None, description="OSArchs lists the \"os_type/os_arch\" combinations the release ships agent binaries for.")
    pinned: Optional[StrictBool] = Field(default=None, description="Pinned indicates this is the version the controller is pinned to.")
    prerelease: Optional[StrictBool] = Field(default=None, description="Prerelease indicates the release is marked as a pre-release upstream.")
    release_notes: Optional[StrictStr] = Field(default=None, description="ReleaseNotes holds the release description as published upstream (typically markdown), so operators can see what changed in a release before pinning to it.")
    version: Optional[StrictStr] = Field(default=None, description="Version is the release tag.")
    __properties: ClassVar[List[str]] = ["assets", "latest", "os_archs", "pinned", "prerelease", "release_notes", "version"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GARMAgentRelease from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in assets (list)
        _items = []
        if self.assets:
            for _item_assets in self.assets:
                if _item_assets:
                    _items.append(_item_assets.to_dict())
            _dict['assets'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GARMAgentRelease from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "assets": [GARMAgentReleaseAsset.from_dict(_item) for _item in obj["assets"]] if obj.get("assets") is not None else None,
            "latest": obj.get("latest"),
            "os_archs": obj.get("os_archs"),
            "pinned": obj.get("pinned"),
            "prerelease": obj.get("prerelease"),
            "release_notes": obj.get("release_notes"),
            "version": obj.get("version")
        })
        return _obj


