# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from garm_client.models.garm_agent_tool import GARMAgentTool
from garm_client.models.metadata_service_access_details import MetadataServiceAccessDetails
from garm_client.models.runner_application_download import RunnerApplicationDownload
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InstanceMetadata(BaseModel):
    """
    InstanceMetadata
    """ # noqa: E501
    agent_mode: Optional[StrictBool] = Field(default=None, description="Agent mode indicates whether or not we need to install the GARM agent on the runner.")
    agent_shell_enabled: Optional[StrictBool] = None
    agent_token: Optional[StrictStr] = None
    agent_tools: Optional[GARMAgentTool] = None
    ca_bundles: Optional[Dict[str, List[StrictInt]]] = None
    extra_specs: Optional[Dict[str, Dict[str, Any]]] = Field(default=None, description="ExtraSpecs represents the extra specs set on the pool or scale set. No secrets should be set in extra specs. Also, the instance metadata should never be saved to disk, and the metadata URL is only accessible during setup of the runner. The API returns unauthorized once the runner transitions to failed/idle.")
    forge_type: Optional[StrictStr] = None
    jit_enabled: Optional[StrictBool] = None
    metadata_access: Optional[MetadataServiceAccessDetails] = None
    runner_labels: Optional[List[StrictStr]] = None
    runner_name: Optional[StrictStr] = None
    runner_registration_url: Optional[StrictStr] = Field(default=None, description="RunnerRegistrationURL is the URL the runner needs to configure itself against. This can be a repository, organization, enterprise (github) or system (gitea)")
    runner_tools: Optional[RunnerApplicationDownload] = None
    __properties: ClassVar[List[str]] = ["agent_mode", "agent_shell_enabled", "agent_token", "agent_tools", "ca_bundles", "extra_specs", "forge_type", "jit_enabled", "metadata_access", "runner_labels", "runner_name", "runner_registration_url", "runner_tools"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstanceMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of agent_tools
        if self.agent_tools:
            _dict['agent_tools'] = self.agent_tools.to_dict()
        # override the default output from pydantic by calling `to_dict()` of metadata_access
        if self.metadata_access:
            _dict['metadata_access'] = self.metadata_access.to_dict()
        # override the default output from pydantic by calling `to_dict()` of runner_tools
        if self.runner_tools:
            _dict['runner_tools'] = self.runner_tools.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstanceMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_mode": obj.get("agent_mode"),
            "agent_shell_enabled": obj.get("agent_shell_enabled"),
            "agent_token": obj.get("agent_token"),
            "agent_tools": GARMAgentTool.from_dict(obj["agent_tools"]) if obj.get("agent_tools") is not None else None,
            "ca_bundles": obj.get("ca_bundles"),
            "extra_specs": obj.get("extra_specs"),
            "forge_type": obj.get("forge_type"),
            "jit_enabled": obj.get("jit_enabled"),
            "metadata_access": MetadataServiceAccessDetails.from_dict(obj["metadata_access"]) if obj.get("metadata_access") is not None else None,
            "runner_labels": obj.get("runner_labels"),
            "runner_name": obj.get("runner_name"),
            "runner_registration_url": obj.get("runner_registration_url"),
            "runner_tools": RunnerApplicationDownload.from_dict(obj["runner_tools"]) if obj.get("runner_tools") is not None else None
        })
        return _obj


