# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Job(BaseModel):
    """
    Job
    """ # noqa: E501
    action: Optional[StrictStr] = Field(default=None, description="Action is the specific activity that triggered the event.")
    completed_at: Optional[datetime] = None
    conclusion: Optional[StrictStr] = Field(default=None, description="Conclusion is the outcome of the job. Possible values: \"success\", \"failure\", \"neutral\", \"cancelled\", \"skipped\", \"timed_out\", \"action_required\"")
    created_at: Optional[datetime] = None
    enterprise_id: Optional[UUID] = None
    id: Optional[StrictInt] = Field(default=None, description="ID is the ID of the job.")
    labels: Optional[List[StrictStr]] = None
    locked_by: Optional[UUID] = None
    name: Optional[StrictStr] = Field(default=None, description="Name is the name if the job that was triggered.")
    org_id: Optional[UUID] = None
    repo_id: Optional[UUID] = Field(default=None, description="The entity that received the hook.  Webhooks may be configured on the repo, the org and/or the enterprise. If we only configure a repo to use garm, we'll only ever receive a webhook from the repo. But if we configure the parent org of the repo and the parent enterprise of the org to use garm, a webhook will be sent for each entity type, in response to one workflow event. Thus, we will get 3 webhooks with the same run_id and job id. Record all involved entities in the same job if we have them configured in garm.")
    repository_name: Optional[StrictStr] = Field(default=None, description="repository in which the job was triggered.")
    repository_owner: Optional[StrictStr] = None
    run_id: Optional[StrictInt] = Field(default=None, description="RunID is the ID of the workflow run. A run may have multiple jobs.")
    runner_group_id: Optional[StrictInt] = None
    runner_group_name: Optional[StrictStr] = None
    runner_id: Optional[StrictInt] = None
    runner_name: Optional[StrictStr] = None
    scaleset_job_id: Optional[StrictStr] = Field(default=None, description="ScaleSetJobID is the job ID when generated for a scale set.")
    started_at: Optional[datetime] = None
    status: Optional[StrictStr] = Field(default=None, description="Status is the phase of the lifecycle that the job is currently in. \"queued\", \"in_progress\" and \"completed\".")
    updated_at: Optional[datetime] = None
    workflow_job_id: Optional[StrictInt] = None
    workflow_run_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["action", "completed_at", "conclusion", "created_at", "enterprise_id", "id", "labels", "locked_by", "name", "org_id", "repo_id", "repository_name", "repository_owner", "run_id", "runner_group_id", "runner_group_name", "runner_id", "runner_name", "scaleset_job_id", "started_at", "status", "updated_at", "workflow_job_id", "workflow_run_url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Job from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Job from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action"),
            "completed_at": obj.get("completed_at"),
            "conclusion": obj.get("conclusion"),
            "created_at": obj.get("created_at"),
            "enterprise_id": obj.get("enterprise_id"),
            "id": obj.get("id"),
            "labels": obj.get("labels"),
            "locked_by": obj.get("locked_by"),
            "name": obj.get("name"),
            "org_id": obj.get("org_id"),
            "repo_id": obj.get("repo_id"),
            "repository_name": obj.get("repository_name"),
            "repository_owner": obj.get("repository_owner"),
            "run_id": obj.get("run_id"),
            "runner_group_id": obj.get("runner_group_id"),
            "runner_group_name": obj.get("runner_group_name"),
            "runner_id": obj.get("runner_id"),
            "runner_name": obj.get("runner_name"),
            "scaleset_job_id": obj.get("scaleset_job_id"),
            "started_at": obj.get("started_at"),
            "status": obj.get("status"),
            "updated_at": obj.get("updated_at"),
            "workflow_job_id": obj.get("workflow_job_id"),
            "workflow_run_url": obj.get("workflow_run_url")
        })
        return _obj


