# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from garm_client.models.forge_endpoint import ForgeEndpoint
from garm_client.models.instance import Instance
from garm_client.models.tag import Tag
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Pool(BaseModel):
    """
    Pool
    """ # noqa: E501
    created_at: Optional[datetime] = None
    enable_shell: Optional[StrictBool] = None
    enabled: Optional[StrictBool] = None
    endpoint: Optional[ForgeEndpoint] = None
    enterprise_id: Optional[StrictStr] = None
    enterprise_name: Optional[StrictStr] = None
    extra_specs: Optional[Dict[str, Any]] = Field(default=None, description="ExtraSpecs is an opaque raw json that gets sent to the provider as part of the bootstrap params for instances. It can contain any kind of data needed by providers. The contents of this field means nothing to garm itself. We don't act on the information in this field at all. We only validate that it's a proper json.")
    flavor: Optional[StrictStr] = None
    generation: Optional[StrictInt] = Field(default=None, description="Generation holds the numeric generation of the pool. This number will be incremented, every time certain settings of the pool, which may influence how runners are created (flavor, specs, image) are changed. When a runner is created, this generation will be copied to the runners as well. That way if some settings diverge, we can target those runners to be recreated.")
    github_runner_group: Optional[StrictStr] = Field(default=None, description="GithubRunnerGroup is the github runner group in which the runners will be added. The runner group must be created by someone with access to the enterprise.", alias="github-runner-group")
    id: Optional[StrictStr] = None
    image: Optional[StrictStr] = None
    instances: Optional[List[Instance]] = None
    max_runners: Optional[StrictInt] = None
    min_idle_runners: Optional[StrictInt] = None
    org_id: Optional[StrictStr] = None
    org_name: Optional[StrictStr] = None
    os_arch: Optional[StrictStr] = None
    os_type: Optional[StrictStr] = None
    priority: Optional[StrictInt] = Field(default=None, description="Priority is the priority of the pool. The higher the number, the higher the priority. When fetching matching pools for a set of tags, the result will be sorted in descending order of priority.")
    provider_name: Optional[StrictStr] = None
    repo_id: Optional[StrictStr] = None
    repo_name: Optional[StrictStr] = None
    runner_bootstrap_timeout: Optional[StrictInt] = None
    runner_prefix: Optional[StrictStr] = None
    tags: Optional[List[Tag]] = None
    template_id: Optional[StrictInt] = None
    template_name: Optional[StrictStr] = None
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["created_at", "enable_shell", "enabled", "endpoint", "enterprise_id", "enterprise_name", "extra_specs", "flavor", "generation", "github-runner-group", "id", "image", "instances", "max_runners", "min_idle_runners", "org_id", "org_name", "os_arch", "os_type", "priority", "provider_name", "repo_id", "repo_name", "runner_bootstrap_timeout", "runner_prefix", "tags", "template_id", "template_name", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Pool from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of endpoint
        if self.endpoint:
            _dict['endpoint'] = self.endpoint.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in instances (list)
        _items = []
        if self.instances:
            for _item_instances in self.instances:
                if _item_instances:
                    _items.append(_item_instances.to_dict())
            _dict['instances'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                if _item_tags:
                    _items.append(_item_tags.to_dict())
            _dict['tags'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Pool from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "enable_shell": obj.get("enable_shell"),
            "enabled": obj.get("enabled"),
            "endpoint": ForgeEndpoint.from_dict(obj["endpoint"]) if obj.get("endpoint") is not None else None,
            "enterprise_id": obj.get("enterprise_id"),
            "enterprise_name": obj.get("enterprise_name"),
            "extra_specs": obj.get("extra_specs"),
            "flavor": obj.get("flavor"),
            "generation": obj.get("generation"),
            "github-runner-group": obj.get("github-runner-group"),
            "id": obj.get("id"),
            "image": obj.get("image"),
            "instances": [Instance.from_dict(_item) for _item in obj["instances"]] if obj.get("instances") is not None else None,
            "max_runners": obj.get("max_runners"),
            "min_idle_runners": obj.get("min_idle_runners"),
            "org_id": obj.get("org_id"),
            "org_name": obj.get("org_name"),
            "os_arch": obj.get("os_arch"),
            "os_type": obj.get("os_type"),
            "priority": obj.get("priority"),
            "provider_name": obj.get("provider_name"),
            "repo_id": obj.get("repo_id"),
            "repo_name": obj.get("repo_name"),
            "runner_bootstrap_timeout": obj.get("runner_bootstrap_timeout"),
            "runner_prefix": obj.get("runner_prefix"),
            "tags": [Tag.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None,
            "template_id": obj.get("template_id"),
            "template_name": obj.get("template_name"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


