# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Proxy(BaseModel):
    """
    Proxy
    """ # noqa: E501
    created_at: Optional[datetime] = None
    description: Optional[StrictStr] = None
    http_proxy: Optional[StrictStr] = Field(default=None, description="HTTPProxy is the proxy URL used for plain HTTP requests.")
    https_proxy: Optional[StrictStr] = Field(default=None, description="HTTPSProxy is the proxy URL used for HTTPS requests.")
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    no_proxy: Optional[StrictStr] = Field(default=None, description="NoProxy is a comma separated list of hosts, domains or CIDRs for which the proxy should be bypassed.")
    updated_at: Optional[datetime] = None
    username: Optional[StrictStr] = Field(default=None, description="Username is the username used to authenticate to the proxy. If set, it will be composed into the final proxy URLs handed to runners.")
    __properties: ClassVar[List[str]] = ["created_at", "description", "http_proxy", "https_proxy", "id", "name", "no_proxy", "updated_at", "username"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Proxy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Proxy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "http_proxy": obj.get("http_proxy"),
            "https_proxy": obj.get("https_proxy"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "no_proxy": obj.get("no_proxy"),
            "updated_at": obj.get("updated_at"),
            "username": obj.get("username")
        })
        return _obj


