# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateControllerParams(BaseModel):
    """
    UpdateControllerParams
    """ # noqa: E501
    agent_url: Optional[StrictStr] = None
    ca_cert_bundle: Optional[Union[Annotated[bytes, Field(strict=True)], Annotated[str, Field(strict=True)]]] = None
    callback_url: Optional[StrictStr] = None
    clear_ca_cert_bundle: Optional[StrictBool] = None
    enable_agent_tools_sync: Optional[StrictBool] = None
    garm_agent_releases_url: Optional[StrictStr] = None
    metadata_url: Optional[StrictStr] = None
    minimum_job_age_backoff: Optional[StrictInt] = None
    webhook_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["agent_url", "ca_cert_bundle", "callback_url", "clear_ca_cert_bundle", "enable_agent_tools_sync", "garm_agent_releases_url", "metadata_url", "minimum_job_age_backoff", "webhook_url"]

    @field_validator('ca_cert_bundle')
    def ca_cert_bundle_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$", value):
            raise ValueError(r"must validate the regular expression /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateControllerParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateControllerParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_url": obj.get("agent_url"),
            "ca_cert_bundle": obj.get("ca_cert_bundle"),
            "callback_url": obj.get("callback_url"),
            "clear_ca_cert_bundle": obj.get("clear_ca_cert_bundle"),
            "enable_agent_tools_sync": obj.get("enable_agent_tools_sync"),
            "garm_agent_releases_url": obj.get("garm_agent_releases_url"),
            "metadata_url": obj.get("metadata_url"),
            "minimum_job_age_backoff": obj.get("minimum_job_age_backoff"),
            "webhook_url": obj.get("webhook_url")
        })
        return _obj


