{
 "title": "GitHub Runner Planner",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total job ingestion (rate of job consumed + job discarded)",
   "type": "timeseries",
   "description": "How many jobs per second is the planner receiving?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "jobs/s" } },
   "targets": [
    {
     "expr": "sum(\n  rate(github_runner_planner_webhook_consumed_total[5m])\n)\n+\nsum(\n  rate(github_runner_planner_webhook_discarded_total[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current pressure of flavors",
   "type": "stat",
   "description": "Which runner flavors are under pressure now?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (flavor) (github_runner_planner_flavor_pressure)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs consumed ratio",
   "type": "timeseries",
   "description": "Ratio of consumed to total (consumed + discarded) jobs per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(github_runner_planner_webhook_consumed_total[5m]))\n/\n(\n  sum(rate(github_runner_planner_webhook_consumed_total[5m]))\n+ sum(rate(github_runner_planner_webhook_discarded_total[5m]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job errors ratio",
   "type": "timeseries",
   "description": "Ratio of errors to total jobs per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(github_runner_planner_webhook_errors_total[5m]))\n/\n(\n  sum(rate(github_runner_planner_webhook_consumed_total[5m]))\n+ sum(rate(github_runner_planner_webhook_errors_total[5m]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average job duration",
   "type": "timeseries",
   "description": "How long do jobs take to run on average?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(github_runner_planner_webhook_job_running_seconds_sum[5m]))\n/\nsum(rate(github_runner_planner_webhook_job_running_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job queue time",
   "type": "timeseries",
   "description": "95% of jobs waited less than this amount of time before starting",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \nsum by (le) (\n  rate(github_runner_planner_webhook_job_waiting_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top repositories",
   "type": "bargauge",
   "description": "Top 20 repository using self-hosted runners per day",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "jobs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, \nsum by (repo) (\n  increase(github_runner_planner_webhook_job_running_seconds_count[1d])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate (by endpoint)",
   "type": "timeseries",
   "description": "How many requests per second are hitting each endpoint?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum by (http_route) (\n  rate(http_server_request_duration_seconds_count{juju_charm=\"github-runner-planner\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration (by endpoint)",
   "type": "timeseries",
   "description": "How slow are requests for each endpoint at the 95th percentile, excluding streaming requests?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, http_route) (\n    rate(http_server_request_duration_seconds_bucket{\n      juju_charm=\"github-runner-planner\",\n      http_route!=\"/api/v1/flavors/{name}/pressure\"\n    }[5m])\n  )\n)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-200 request rate (by endpoint)",
   "type": "timeseries",
   "description": "Which endpoints are returning errors?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum by (http_route) (\n  rate(http_server_request_duration_seconds_count{\n    juju_charm=\"github-runner-planner\",\n    http_response_status_code!=\"200\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}