# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.repository import Repository

class TestRepository(unittest.TestCase):
    """Repository unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Repository:
        """Test Repository
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Repository`
        """
        model = Repository()
        if include_optional:
            return Repository(
                agent_mode = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                credentials = garm_client.models.forge_credentials.ForgeCredentials(
                    api_base_url = '', 
                    auth_type = '', 
                    base_url = '', 
                    ca_bundle = [
                        56
                        ], 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    description = '', 
                    endpoint = garm_client.models.forge_endpoint.ForgeEndpoint(
                        api_base_url = '', 
                        base_url = '', 
                        ca_cert_bundle = [
                            56
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        description = '', 
                        endpoint_type = '', 
                        name = '', 
                        tools_metadata_url = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        upload_base_url = '', 
                        use_internal_tools_metadata = True, ), 
                    enterprises = [
                        garm_client.models.enterprise.Enterprise(
                            agent_mode = True, 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            credentials = garm_client.models.forge_credentials.ForgeCredentials(
                                api_base_url = '', 
                                base_url = '', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                description = '', 
                                forge_type = '', 
                                id = 56, 
                                name = '', 
                                organizations = [
                                    garm_client.models.organization.Organization(
                                        agent_mode = True, 
                                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        credentials_id = 56, 
                                        credentials_name = '', 
                                        events = [
                                            garm_client.models.entity_event.EntityEvent(
                                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                event_level = '', 
                                                event_type = '', 
                                                id = 56, 
                                                message = '', )
                                            ], 
                                        id = '', 
                                        name = '', 
                                        pool = [
                                            garm_client.models.pool.Pool(
                                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                enable_shell = True, 
                                                enabled = True, 
                                                enterprise_id = '', 
                                                enterprise_name = '', 
                                                extra_specs = garm_client.models.extra_specs.extra_specs(), 
                                                flavor = '', 
                                                generation = 56, 
                                                github_runner_group = '', 
                                                id = '', 
                                                image = '', 
                                                instances = [
                                                    garm_client.models.instance.Instance(
                                                        addresses = [
                                                            garm_client.models.address.Address(
                                                                address = '', 
                                                                type = '', )
                                                            ], 
                                                        agent_id = 56, 
                                                        capabilities = garm_client.models.agent_capabilities.AgentCapabilities(
                                                            has_shell = True, ), 
                                                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                        generation = 56, 
                                                        github_runner_group = '', 
                                                        heartbeat = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                        id = '', 
                                                        job = garm_client.models.job.Job(
                                                            action = '', 
                                                            completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                            conclusion = '', 
                                                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                            enterprise_id = '', 
                                                            id = 56, 
                                                            labels = [
                                                                ''
                                                                ], 
                                                            locked_by = '', 
                                                            name = '', 
                                                            org_id = '', 
                                                            repo_id = '', 
                                                            repository_name = '', 
                                                            repository_owner = '', 
                                                            run_id = 56, 
                                                            runner_group_id = 56, 
                                                            runner_group_name = '', 
                                                            runner_id = 56, 
                                                            runner_name = '', 
                                                            scaleset_job_id = '', 
                                                            started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                            status = '', 
                                                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                            workflow_job_id = 56, 
                                                            workflow_run_url = '', ), 
                                                        name = '', 
                                                        os_arch = '', 
                                                        os_name = '', 
                                                        os_type = '', 
                                                        os_version = '', 
                                                        pool_id = '', 
                                                        provider_fault = [
                                                            56
                                                            ], 
                                                        provider_id = '', 
                                                        provider_name = '', 
                                                        runner_status = '', 
                                                        scale_set_id = 56, 
                                                        status = '', 
                                                        status_messages = [
                                                            garm_client.models.status_message.StatusMessage(
                                                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                                message = '', )
                                                            ], 
                                                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                                    ], 
                                                max_runners = 56, 
                                                min_idle_runners = 56, 
                                                org_id = '', 
                                                org_name = '', 
                                                os_arch = '', 
                                                os_type = '', 
                                                priority = 56, 
                                                provider_name = '', 
                                                repo_id = '', 
                                                repo_name = '', 
                                                runner_bootstrap_timeout = 56, 
                                                runner_prefix = '', 
                                                tags = [
                                                    garm_client.models.tag.Tag(
                                                        id = '', 
                                                        name = '', )
                                                    ], 
                                                template_id = 56, 
                                                template_name = '', 
                                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                            ], 
                                        pool_balancing_type = '', 
                                        pool_manager_status = garm_client.models.pool_manager_status.PoolManagerStatus(
                                            failure_reason = '', 
                                            running = True, ), 
                                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                    ], 
                                rate_limit = garm_client.models.github_rate_limit.GithubRateLimit(
                                    limit = 56, 
                                    remaining = 56, 
                                    reset = 56, 
                                    used = 56, ), 
                                repositories = [
                                    garm_client.models.repository.Repository(
                                        agent_mode = True, 
                                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        credentials_id = 56, 
                                        credentials_name = '', 
                                        id = '', 
                                        name = '', 
                                        owner = '', 
                                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                    ], 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                upload_base_url = '', ), 
                            credentials_id = 56, 
                            credentials_name = '', 
                            events = [
                                garm_client.models.entity_event.EntityEvent(
                                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    id = 56, 
                                    message = '', )
                                ], 
                            id = '', 
                            name = '', 
                            pool = [
                                garm_client.models.pool.Pool(
                                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    enable_shell = True, 
                                    enabled = True, 
                                    enterprise_id = '', 
                                    enterprise_name = '', 
                                    extra_specs = garm_client.models.extra_specs.extra_specs(), 
                                    flavor = '', 
                                    generation = 56, 
                                    github_runner_group = '', 
                                    id = '', 
                                    image = '', 
                                    max_runners = 56, 
                                    min_idle_runners = 56, 
                                    org_id = '', 
                                    org_name = '', 
                                    priority = 56, 
                                    provider_name = '', 
                                    repo_id = '', 
                                    repo_name = '', 
                                    runner_bootstrap_timeout = 56, 
                                    runner_prefix = '', 
                                    template_id = 56, 
                                    template_name = '', 
                                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            pool_balancing_type = '', 
                            pool_manager_status = garm_client.models.pool_manager_status.PoolManagerStatus(
                                failure_reason = '', 
                                running = True, ), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    forge_type = '', 
                    id = 56, 
                    name = '', 
                    organizations = [
                        garm_client.models.organization.Organization(
                            agent_mode = True, 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            credentials_id = 56, 
                            credentials_name = '', 
                            id = '', 
                            name = '', 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    rate_limit = garm_client.models.github_rate_limit.GithubRateLimit(
                        limit = 56, 
                        remaining = 56, 
                        reset = 56, 
                        used = 56, ), 
                    repositories = [
                        garm_client.models.repository.Repository(
                            agent_mode = True, 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            credentials_id = 56, 
                            credentials_name = '', 
                            id = '', 
                            name = '', 
                            owner = '', 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    upload_base_url = '', ),
                credentials_id = 56,
                credentials_name = '',
                endpoint = garm_client.models.forge_endpoint.ForgeEndpoint(
                    api_base_url = '', 
                    base_url = '', 
                    ca_cert_bundle = [
                        56
                        ], 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    description = '', 
                    endpoint_type = '', 
                    name = '', 
                    tools_metadata_url = '', 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    upload_base_url = '', 
                    use_internal_tools_metadata = True, ),
                events = [
                    garm_client.models.entity_event.EntityEvent(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        event_level = '', 
                        event_type = '', 
                        id = 56, 
                        message = '', )
                    ],
                id = '',
                name = '',
                owner = '',
                pool = [
                    garm_client.models.pool.Pool(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        enable_shell = True, 
                        enabled = True, 
                        endpoint = garm_client.models.forge_endpoint.ForgeEndpoint(
                            api_base_url = '', 
                            base_url = '', 
                            ca_cert_bundle = [
                                56
                                ], 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            description = '', 
                            endpoint_type = '', 
                            name = '', 
                            tools_metadata_url = '', 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            upload_base_url = '', 
                            use_internal_tools_metadata = True, ), 
                        enterprise_id = '', 
                        enterprise_name = '', 
                        extra_specs = garm_client.models.extra_specs.extra_specs(), 
                        flavor = '', 
                        generation = 56, 
                        github_runner_group = '', 
                        id = '', 
                        image = '', 
                        instances = [
                            garm_client.models.instance.Instance(
                                addresses = [
                                    garm_client.models.address.Address(
                                        address = '', 
                                        type = '', )
                                    ], 
                                agent_id = 56, 
                                capabilities = garm_client.models.agent_capabilities.AgentCapabilities(
                                    has_shell = True, ), 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                generation = 56, 
                                github_runner_group = '', 
                                heartbeat = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                id = '', 
                                job = garm_client.models.job.Job(
                                    action = '', 
                                    completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    conclusion = '', 
                                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    enterprise_id = '', 
                                    id = 56, 
                                    labels = [
                                        ''
                                        ], 
                                    locked_by = '', 
                                    name = '', 
                                    org_id = '', 
                                    repo_id = '', 
                                    repository_name = '', 
                                    repository_owner = '', 
                                    run_id = 56, 
                                    runner_group_id = 56, 
                                    runner_group_name = '', 
                                    runner_id = 56, 
                                    runner_name = '', 
                                    scaleset_job_id = '', 
                                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    status = '', 
                                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    workflow_job_id = 56, 
                                    workflow_run_url = '', ), 
                                name = '', 
                                os_arch = '', 
                                os_name = '', 
                                os_type = '', 
                                os_version = '', 
                                pool_id = '', 
                                provider_fault = [
                                    56
                                    ], 
                                provider_id = '', 
                                provider_name = '', 
                                runner_status = '', 
                                scale_set_id = 56, 
                                status = '', 
                                status_messages = [
                                    garm_client.models.status_message.StatusMessage(
                                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        event_level = '', 
                                        event_type = '', 
                                        message = '', )
                                    ], 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], 
                        max_runners = 56, 
                        min_idle_runners = 56, 
                        org_id = '', 
                        org_name = '', 
                        os_arch = '', 
                        os_type = '', 
                        priority = 56, 
                        provider_name = '', 
                        repo_id = '', 
                        repo_name = '', 
                        runner_bootstrap_timeout = 56, 
                        runner_prefix = '', 
                        tags = [
                            garm_client.models.tag.Tag(
                                id = '', 
                                name = '', )
                            ], 
                        template_id = 56, 
                        template_name = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pool_balancing_type = '',
                pool_manager_status = garm_client.models.pool_manager_status.PoolManagerStatus(
                    failure_reason = '', 
                    running = True, ),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return Repository(
        )
        """

    def testRepository(self):
        """Test Repository"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
