# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.update_proxy_params import UpdateProxyParams

class TestUpdateProxyParams(unittest.TestCase):
    """UpdateProxyParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateProxyParams:
        """Test UpdateProxyParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateProxyParams`
        """
        model = UpdateProxyParams()
        if include_optional:
            return UpdateProxyParams(
                description = '',
                http_proxy = '',
                https_proxy = '',
                name = '',
                no_proxy = '',
                password = '',
                username = ''
            )
        else:
            return UpdateProxyParams(
        )
        """

    def testUpdateProxyParams(self):
        """Test UpdateProxyParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
