# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.objects_api import ObjectsApi


class TestObjectsApi(unittest.TestCase):
    """ObjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ObjectsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_file_object(self) -> None:
        """Test case for delete_file_object

        Delete a file object.
        """
        pass

    def test_get_file_object(self) -> None:
        """Test case for get_file_object

        Get a file object.
        """
        pass

    def test_list_file_objects(self) -> None:
        """Test case for list_file_objects

        List file objects.
        """
        pass

    def test_update_file_object(self) -> None:
        """Test case for update_file_object

        Update a file object.
        """
        pass


if __name__ == '__main__':
    unittest.main()
