# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.tools_api import ToolsApi


class TestToolsApi(unittest.TestCase):
    """ToolsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ToolsApi()

    def tearDown(self) -> None:
        pass

    def test_admin_garm_agent_list(self) -> None:
        """Test case for admin_garm_agent_list

        List GARM agent tools for admin users.
        """
        pass

    def test_upload_garm_agent_tool(self) -> None:
        """Test case for upload_garm_agent_tool

        Upload a GARM agent tool binary.
        """
        pass


if __name__ == '__main__':
    unittest.main()
