# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.controller_api import ControllerApi


class TestControllerApi(unittest.TestCase):
    """ControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ControllerApi()

    def tearDown(self) -> None:
        pass

    def test_force_tools_sync(self) -> None:
        """Test case for force_tools_sync

        Force immediate sync of GARM agent tools.
        """
        pass

    def test_update_controller(self) -> None:
        """Test case for update_controller

        Update controller.
        """
        pass


if __name__ == '__main__':
    unittest.main()
