# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.login_api import LoginApi


class TestLoginApi(unittest.TestCase):
    """LoginApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LoginApi()

    def tearDown(self) -> None:
        pass

    def test_login(self) -> None:
        """Test case for login

        Logs in a user and returns a JWT token.
        """
        pass


if __name__ == '__main__':
    unittest.main()
