# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.enterprises_api import EnterprisesApi


class TestEnterprisesApi(unittest.TestCase):
    """EnterprisesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnterprisesApi()

    def tearDown(self) -> None:
        pass

    def test_create_enterprise(self) -> None:
        """Test case for create_enterprise

        Create enterprise with the given parameters.
        """
        pass

    def test_create_enterprise_pool(self) -> None:
        """Test case for create_enterprise_pool

        Create enterprise pool with the parameters given.
        """
        pass

    def test_create_enterprise_scale_set(self) -> None:
        """Test case for create_enterprise_scale_set

        Create enterprise pool with the parameters given.
        """
        pass

    def test_delete_enterprise(self) -> None:
        """Test case for delete_enterprise

        Delete enterprise by ID.
        """
        pass

    def test_delete_enterprise_pool(self) -> None:
        """Test case for delete_enterprise_pool

        Delete enterprise pool by ID.
        """
        pass

    def test_get_enterprise(self) -> None:
        """Test case for get_enterprise

        Get enterprise by ID.
        """
        pass

    def test_get_enterprise_pool(self) -> None:
        """Test case for get_enterprise_pool

        Get enterprise pool by ID.
        """
        pass

    def test_list_enterprise_instances(self) -> None:
        """Test case for list_enterprise_instances

        List enterprise instances.
        """
        pass

    def test_list_enterprise_pools(self) -> None:
        """Test case for list_enterprise_pools

        List enterprise pools.
        """
        pass

    def test_list_enterprise_scale_sets(self) -> None:
        """Test case for list_enterprise_scale_sets

        List enterprise scale sets.
        """
        pass

    def test_list_enterprises(self) -> None:
        """Test case for list_enterprises

        List all enterprises.
        """
        pass

    def test_update_enterprise(self) -> None:
        """Test case for update_enterprise

        Update enterprise with the given parameters.
        """
        pass

    def test_update_enterprise_pool(self) -> None:
        """Test case for update_enterprise_pool

        Update enterprise pool with the parameters given.
        """
        pass


if __name__ == '__main__':
    unittest.main()
