# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.credentials_api import CredentialsApi


class TestCredentialsApi(unittest.TestCase):
    """CredentialsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CredentialsApi()

    def tearDown(self) -> None:
        pass

    def test_create_credentials(self) -> None:
        """Test case for create_credentials

        Create a GitHub credential.
        """
        pass

    def test_create_gitea_credentials(self) -> None:
        """Test case for create_gitea_credentials

        Create a Gitea credential.
        """
        pass

    def test_delete_credentials(self) -> None:
        """Test case for delete_credentials

        Delete a GitHub credential.
        """
        pass

    def test_delete_gitea_credentials(self) -> None:
        """Test case for delete_gitea_credentials

        Delete a Gitea credential.
        """
        pass

    def test_get_credentials(self) -> None:
        """Test case for get_credentials

        Get a GitHub credential.
        """
        pass

    def test_get_gitea_credentials(self) -> None:
        """Test case for get_gitea_credentials

        Get a Gitea credential.
        """
        pass

    def test_list_credentials(self) -> None:
        """Test case for list_credentials

        List all credentials.
        """
        pass

    def test_list_gitea_credentials(self) -> None:
        """Test case for list_gitea_credentials

        List all credentials.
        """
        pass

    def test_update_credentials(self) -> None:
        """Test case for update_credentials

        Update a GitHub credential.
        """
        pass

    def test_update_gitea_credentials(self) -> None:
        """Test case for update_gitea_credentials

        Update a Gitea credential.
        """
        pass


if __name__ == '__main__':
    unittest.main()
