# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.create_repo_params import CreateRepoParams

class TestCreateRepoParams(unittest.TestCase):
    """CreateRepoParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateRepoParams:
        """Test CreateRepoParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateRepoParams`
        """
        model = CreateRepoParams()
        if include_optional:
            return CreateRepoParams(
                agent_mode = True,
                credentials_name = '',
                forge_type = '',
                name = '',
                owner = '',
                pool_balancer_type = '',
                webhook_secret = ''
            )
        else:
            return CreateRepoParams(
        )
        """

    def testCreateRepoParams(self):
        """Test CreateRepoParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
