# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.instance import Instance

class TestInstance(unittest.TestCase):
    """Instance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Instance:
        """Test Instance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Instance`
        """
        model = Instance()
        if include_optional:
            return Instance(
                addresses = [
                    garm_client.models.address.Address(
                        address = '', 
                        type = '', )
                    ],
                agent_id = 56,
                capabilities = garm_client.models.agent_capabilities.AgentCapabilities(
                    has_shell = True, ),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                generation = 56,
                github_runner_group = '',
                heartbeat = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                job = garm_client.models.job.Job(
                    action = '', 
                    completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    conclusion = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    enterprise_id = '', 
                    id = 56, 
                    labels = [
                        ''
                        ], 
                    locked_by = '', 
                    name = '', 
                    org_id = '', 
                    repo_id = '', 
                    repository_name = '', 
                    repository_owner = '', 
                    run_id = 56, 
                    runner_group_id = 56, 
                    runner_group_name = '', 
                    runner_id = 56, 
                    runner_name = '', 
                    scaleset_job_id = '', 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    status = '', 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    workflow_job_id = 56, 
                    workflow_run_url = '', ),
                name = '',
                os_arch = '',
                os_name = '',
                os_type = '',
                os_version = '',
                pool_id = '',
                provider_fault = [
                    56
                    ],
                provider_id = '',
                provider_name = '',
                runner_status = '',
                scale_set_id = 56,
                status = '',
                status_messages = [
                    garm_client.models.status_message.StatusMessage(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        event_level = '', 
                        event_type = '', 
                        message = '', )
                    ],
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return Instance(
        )
        """

    def testInstance(self):
        """Test Instance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
