# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.scalesets_api import ScalesetsApi


class TestScalesetsApi(unittest.TestCase):
    """ScalesetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScalesetsApi()

    def tearDown(self) -> None:
        pass

    def test_create_enterprise_scale_set(self) -> None:
        """Test case for create_enterprise_scale_set

        Create enterprise pool with the parameters given.
        """
        pass

    def test_create_org_scale_set(self) -> None:
        """Test case for create_org_scale_set

        Create organization scale set with the parameters given.
        """
        pass

    def test_create_repo_scale_set(self) -> None:
        """Test case for create_repo_scale_set

        Create repository scale set with the parameters given.
        """
        pass

    def test_delete_scale_set(self) -> None:
        """Test case for delete_scale_set

        Delete scale set by ID.
        """
        pass

    def test_get_scale_set(self) -> None:
        """Test case for get_scale_set

        Get scale set by ID.
        """
        pass

    def test_list_enterprise_scale_sets(self) -> None:
        """Test case for list_enterprise_scale_sets

        List enterprise scale sets.
        """
        pass

    def test_list_org_scale_sets(self) -> None:
        """Test case for list_org_scale_sets

        List organization scale sets.
        """
        pass

    def test_list_repo_scale_sets(self) -> None:
        """Test case for list_repo_scale_sets

        List repository scale sets.
        """
        pass

    def test_list_scalesets(self) -> None:
        """Test case for list_scalesets

        List all scalesets.
        """
        pass

    def test_update_scale_set(self) -> None:
        """Test case for update_scale_set

        Update scale set by ID.
        """
        pass


if __name__ == '__main__':
    unittest.main()
