# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.controller_info import ControllerInfo

class TestControllerInfo(unittest.TestCase):
    """ControllerInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ControllerInfo:
        """Test ControllerInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ControllerInfo`
        """
        model = ControllerInfo()
        if include_optional:
            return ControllerInfo(
                agent_url = '',
                ca_cert_bundle = [
                    56
                    ],
                cached_garm_agent_release_fetched_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                callback_url = '',
                controller_id = '',
                controller_webhook_url = '',
                enable_agent_tools_sync = True,
                garm_agent_releases_url = '',
                hostname = '',
                metadata_url = '',
                minimum_job_age_backoff = 56,
                version = '',
                webhook_url = ''
            )
        else:
            return ControllerInfo(
        )
        """

    def testControllerInfo(self):
        """Test ControllerInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
