# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.metrics_token_api import MetricsTokenApi


class TestMetricsTokenApi(unittest.TestCase):
    """MetricsTokenApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetricsTokenApi()

    def tearDown(self) -> None:
        pass

    def test_get_metrics_token(self) -> None:
        """Test case for get_metrics_token

        Returns a JWT token that can be used to access the metrics endpoint.
        """
        pass


if __name__ == '__main__':
    unittest.main()
