# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.new_user_params import NewUserParams

class TestNewUserParams(unittest.TestCase):
    """NewUserParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewUserParams:
        """Test NewUserParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewUserParams`
        """
        model = NewUserParams()
        if include_optional:
            return NewUserParams(
                email = '',
                full_name = '',
                password = '',
                username = ''
            )
        else:
            return NewUserParams(
        )
        """

    def testNewUserParams(self):
        """Test NewUserParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
