# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.instance_metadata import InstanceMetadata

class TestInstanceMetadata(unittest.TestCase):
    """InstanceMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstanceMetadata:
        """Test InstanceMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstanceMetadata`
        """
        model = InstanceMetadata()
        if include_optional:
            return InstanceMetadata(
                agent_mode = True,
                agent_shell_enabled = True,
                agent_token = '',
                agent_tools = garm_client.models.garm_agent_tool.GARMAgentTool(
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    description = '', 
                    download_url = '', 
                    file_type = '', 
                    id = 56, 
                    name = '', 
                    origin = '', 
                    os_arch = '', 
                    os_type = '', 
                    sha256sum = '', 
                    size = 56, 
                    source = '', 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    version = '', ),
                ca_bundles = {
                    'key' : [
                        56
                        ]
                    },
                extra_specs = {
                    'key' : None
                    },
                forge_type = '',
                jit_enabled = True,
                metadata_access = garm_client.models.metadata_service_access_details.MetadataServiceAccessDetails(
                    agent_url = '', 
                    callback_url = '', 
                    metadata_url = '', ),
                runner_labels = [
                    ''
                    ],
                runner_name = '',
                runner_registration_url = '',
                runner_tools = garm_client.models.runner_application_download_represents_a_binary_for_the_self_hosted_runner_application_that_can_be_downloaded/.RunnerApplicationDownload represents a binary for the self-hosted runner application that can be downloaded.(
                    architecture = '', 
                    download_url = '', 
                    filename = '', 
                    os = '', 
                    sha256_checksum = '', 
                    temp_download_token = '', )
            )
        else:
            return InstanceMetadata(
        )
        """

    def testInstanceMetadata(self):
        """Test InstanceMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
