# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.endpoints_api import EndpointsApi


class TestEndpointsApi(unittest.TestCase):
    """EndpointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EndpointsApi()

    def tearDown(self) -> None:
        pass

    def test_create_gitea_endpoint(self) -> None:
        """Test case for create_gitea_endpoint

        Create a Gitea Endpoint.
        """
        pass

    def test_create_github_endpoint(self) -> None:
        """Test case for create_github_endpoint

        Create a GitHub Endpoint.
        """
        pass

    def test_delete_gitea_endpoint(self) -> None:
        """Test case for delete_gitea_endpoint

        Delete a Gitea Endpoint.
        """
        pass

    def test_delete_github_endpoint(self) -> None:
        """Test case for delete_github_endpoint

        Delete a GitHub Endpoint.
        """
        pass

    def test_get_gitea_endpoint(self) -> None:
        """Test case for get_gitea_endpoint

        Get a Gitea Endpoint.
        """
        pass

    def test_get_github_endpoint(self) -> None:
        """Test case for get_github_endpoint

        Get a GitHub Endpoint.
        """
        pass

    def test_list_gitea_endpoints(self) -> None:
        """Test case for list_gitea_endpoints

        List all Gitea Endpoints.
        """
        pass

    def test_list_github_endpoints(self) -> None:
        """Test case for list_github_endpoints

        List all GitHub Endpoints.
        """
        pass

    def test_update_gitea_endpoint(self) -> None:
        """Test case for update_gitea_endpoint

        Update a Gitea Endpoint.
        """
        pass

    def test_update_github_endpoint(self) -> None:
        """Test case for update_github_endpoint

        Update a GitHub Endpoint.
        """
        pass


if __name__ == '__main__':
    unittest.main()
