# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.create_pool_params import CreatePoolParams

class TestCreatePoolParams(unittest.TestCase):
    """CreatePoolParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePoolParams:
        """Test CreatePoolParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePoolParams`
        """
        model = CreatePoolParams()
        if include_optional:
            return CreatePoolParams(
                enable_shell = True,
                enabled = True,
                extra_specs = None,
                flavor = '',
                github_runner_group = '',
                image = '',
                max_runners = 56,
                min_idle_runners = 56,
                os_arch = '',
                os_type = '',
                priority = 56,
                provider_name = '',
                runner_bootstrap_timeout = 56,
                runner_prefix = '',
                tags = [
                    ''
                    ],
                template_id = 56
            )
        else:
            return CreatePoolParams(
        )
        """

    def testCreatePoolParams(self):
        """Test CreatePoolParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
