# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.instances_api import InstancesApi


class TestInstancesApi(unittest.TestCase):
    """InstancesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InstancesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_instance(self) -> None:
        """Test case for delete_instance

        Delete runner instance by name.
        """
        pass

    def test_get_instance(self) -> None:
        """Test case for get_instance

        Get runner instance by name.
        """
        pass

    def test_list_enterprise_instances(self) -> None:
        """Test case for list_enterprise_instances

        List enterprise instances.
        """
        pass

    def test_list_instances(self) -> None:
        """Test case for list_instances

        Get all runners' instances.
        """
        pass

    def test_list_org_instances(self) -> None:
        """Test case for list_org_instances

        List organization instances.
        """
        pass

    def test_list_pool_instances(self) -> None:
        """Test case for list_pool_instances

        List runner instances in a pool.
        """
        pass

    def test_list_repo_instances(self) -> None:
        """Test case for list_repo_instances

        List repository instances.
        """
        pass

    def test_list_scale_set_instances(self) -> None:
        """Test case for list_scale_set_instances

        List runner instances in a scale set.
        """
        pass


if __name__ == '__main__':
    unittest.main()
