# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.create_github_credentials_params import CreateGithubCredentialsParams

class TestCreateGithubCredentialsParams(unittest.TestCase):
    """CreateGithubCredentialsParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateGithubCredentialsParams:
        """Test CreateGithubCredentialsParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateGithubCredentialsParams`
        """
        model = CreateGithubCredentialsParams()
        if include_optional:
            return CreateGithubCredentialsParams(
                app = garm_client.models.github_app.GithubApp(
                    app_id = 56, 
                    installation_id = 56, 
                    private_key_bytes = 'YQ==', ),
                auth_type = '',
                description = '',
                endpoint = '',
                name = '',
                pat = garm_client.models.github_pat.GithubPAT(
                    oauth2_token = '', )
            )
        else:
            return CreateGithubCredentialsParams(
        )
        """

    def testCreateGithubCredentialsParams(self):
        """Test CreateGithubCredentialsParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
