# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.controller_info_api import ControllerInfoApi


class TestControllerInfoApi(unittest.TestCase):
    """ControllerInfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ControllerInfoApi()

    def tearDown(self) -> None:
        pass

    def test_controller_info(self) -> None:
        """Test case for controller_info

        Get controller info.
        """
        pass


if __name__ == '__main__':
    unittest.main()
