# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.metadata_service_access_details import MetadataServiceAccessDetails

class TestMetadataServiceAccessDetails(unittest.TestCase):
    """MetadataServiceAccessDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetadataServiceAccessDetails:
        """Test MetadataServiceAccessDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetadataServiceAccessDetails`
        """
        model = MetadataServiceAccessDetails()
        if include_optional:
            return MetadataServiceAccessDetails(
                agent_url = '',
                callback_url = '',
                metadata_url = ''
            )
        else:
            return MetadataServiceAccessDetails(
        )
        """

    def testMetadataServiceAccessDetails(self):
        """Test MetadataServiceAccessDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
