# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.proxies_api import ProxiesApi


class TestProxiesApi(unittest.TestCase):
    """ProxiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProxiesApi()

    def tearDown(self) -> None:
        pass

    def test_create_proxy(self) -> None:
        """Test case for create_proxy

        Create proxy with the parameters given.
        """
        pass

    def test_delete_proxy(self) -> None:
        """Test case for delete_proxy

        Delete proxy by ID.
        """
        pass

    def test_get_proxy(self) -> None:
        """Test case for get_proxy

        Get proxy by ID.
        """
        pass

    def test_list_proxies(self) -> None:
        """Test case for list_proxies

        List proxies.
        """
        pass

    def test_update_proxy(self) -> None:
        """Test case for update_proxy

        Update proxy with the parameters given.
        """
        pass


if __name__ == '__main__':
    unittest.main()
