# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.hook_info import HookInfo

class TestHookInfo(unittest.TestCase):
    """HookInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HookInfo:
        """Test HookInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HookInfo`
        """
        model = HookInfo()
        if include_optional:
            return HookInfo(
                active = True,
                events = [
                    ''
                    ],
                id = 56,
                insecure_ssl = True,
                url = ''
            )
        else:
            return HookInfo(
        )
        """

    def testHookInfo(self):
        """Test HookInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
