# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.file_object_paginated_response import FileObjectPaginatedResponse

class TestFileObjectPaginatedResponse(unittest.TestCase):
    """FileObjectPaginatedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileObjectPaginatedResponse:
        """Test FileObjectPaginatedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileObjectPaginatedResponse`
        """
        model = FileObjectPaginatedResponse()
        if include_optional:
            return FileObjectPaginatedResponse(
                current_page = 56,
                next_page = 56,
                pages = 56,
                previous_page = 56,
                results = [
                    garm_client.models.file_object_paginated_response_results_inner.FileObjectPaginatedResponse_results_inner(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        description = '', 
                        file_type = '', 
                        id = 56, 
                        name = '', 
                        sha256 = '', 
                        size = 56, 
                        tags = [
                            ''
                            ], 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total_count = 56
            )
        else:
            return FileObjectPaginatedResponse(
        )
        """

    def testFileObjectPaginatedResponse(self):
        """Test FileObjectPaginatedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
