# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.templates_api import TemplatesApi


class TestTemplatesApi(unittest.TestCase):
    """TemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_create_template(self) -> None:
        """Test case for create_template

        Create template with the parameters given.
        """
        pass

    def test_delete_template(self) -> None:
        """Test case for delete_template

        Get template by ID.
        """
        pass

    def test_get_template(self) -> None:
        """Test case for get_template

        Get template by ID.
        """
        pass

    def test_list_templates(self) -> None:
        """Test case for list_templates

        List templates.
        """
        pass

    def test_restore_templates(self) -> None:
        """Test case for restore_templates

        Create template with the parameters given.
        """
        pass

    def test_update_template(self) -> None:
        """Test case for update_template

        Update template with the parameters given.
        """
        pass


if __name__ == '__main__':
    unittest.main()
