# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.hooks_api import HooksApi


class TestHooksApi(unittest.TestCase):
    """HooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HooksApi()

    def tearDown(self) -> None:
        pass

    def test_get_org_webhook_info(self) -> None:
        """Test case for get_org_webhook_info

        Get information about the GARM installed webhook on an organization.
        """
        pass

    def test_get_repo_webhook_info(self) -> None:
        """Test case for get_repo_webhook_info

        Get information about the GARM installed webhook on a repository.
        """
        pass

    def test_install_org_webhook(self) -> None:
        """Test case for install_org_webhook

        """
        pass

    def test_install_repo_webhook(self) -> None:
        """Test case for install_repo_webhook

        """
        pass

    def test_uninstall_org_webhook(self) -> None:
        """Test case for uninstall_org_webhook

        Uninstall organization webhook.
        """
        pass

    def test_uninstall_repo_webhook(self) -> None:
        """Test case for uninstall_repo_webhook

        Uninstall organization webhook.
        """
        pass


if __name__ == '__main__':
    unittest.main()
