# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.create_template_params import CreateTemplateParams

class TestCreateTemplateParams(unittest.TestCase):
    """CreateTemplateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTemplateParams:
        """Test CreateTemplateParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTemplateParams`
        """
        model = CreateTemplateParams()
        if include_optional:
            return CreateTemplateParams(
                data = [
                    56
                    ],
                description = '',
                forge_type = '',
                name = '',
                os_type = ''
            )
        else:
            return CreateTemplateParams(
        )
        """

    def testCreateTemplateParams(self):
        """Test CreateTemplateParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
