# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.pools_api import PoolsApi


class TestPoolsApi(unittest.TestCase):
    """PoolsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PoolsApi()

    def tearDown(self) -> None:
        pass

    def test_create_enterprise_pool(self) -> None:
        """Test case for create_enterprise_pool

        Create enterprise pool with the parameters given.
        """
        pass

    def test_create_org_pool(self) -> None:
        """Test case for create_org_pool

        Create organization pool with the parameters given.
        """
        pass

    def test_create_repo_pool(self) -> None:
        """Test case for create_repo_pool

        Create repository pool with the parameters given.
        """
        pass

    def test_delete_enterprise_pool(self) -> None:
        """Test case for delete_enterprise_pool

        Delete enterprise pool by ID.
        """
        pass

    def test_delete_org_pool(self) -> None:
        """Test case for delete_org_pool

        Delete organization pool by ID.
        """
        pass

    def test_delete_pool(self) -> None:
        """Test case for delete_pool

        Delete pool by ID.
        """
        pass

    def test_delete_repo_pool(self) -> None:
        """Test case for delete_repo_pool

        Delete repository pool by ID.
        """
        pass

    def test_get_enterprise_pool(self) -> None:
        """Test case for get_enterprise_pool

        Get enterprise pool by ID.
        """
        pass

    def test_get_org_pool(self) -> None:
        """Test case for get_org_pool

        Get organization pool by ID.
        """
        pass

    def test_get_pool(self) -> None:
        """Test case for get_pool

        Get pool by ID.
        """
        pass

    def test_get_repo_pool(self) -> None:
        """Test case for get_repo_pool

        Get repository pool by ID.
        """
        pass

    def test_list_enterprise_pools(self) -> None:
        """Test case for list_enterprise_pools

        List enterprise pools.
        """
        pass

    def test_list_org_pools(self) -> None:
        """Test case for list_org_pools

        List organization pools.
        """
        pass

    def test_list_pools(self) -> None:
        """Test case for list_pools

        List all pools.
        """
        pass

    def test_list_repo_pools(self) -> None:
        """Test case for list_repo_pools

        List repository pools.
        """
        pass

    def test_update_enterprise_pool(self) -> None:
        """Test case for update_enterprise_pool

        Update enterprise pool with the parameters given.
        """
        pass

    def test_update_org_pool(self) -> None:
        """Test case for update_org_pool

        Update organization pool with the parameters given.
        """
        pass

    def test_update_pool(self) -> None:
        """Test case for update_pool

        Update pool by ID.
        """
        pass

    def test_update_repo_pool(self) -> None:
        """Test case for update_repo_pool

        Update repository pool with the parameters given.
        """
        pass


if __name__ == '__main__':
    unittest.main()
