# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.update_gitea_endpoint_params import UpdateGiteaEndpointParams

class TestUpdateGiteaEndpointParams(unittest.TestCase):
    """UpdateGiteaEndpointParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateGiteaEndpointParams:
        """Test UpdateGiteaEndpointParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateGiteaEndpointParams`
        """
        model = UpdateGiteaEndpointParams()
        if include_optional:
            return UpdateGiteaEndpointParams(
                api_base_url = '',
                base_url = '',
                ca_cert_bundle = 'YQ==',
                description = '',
                tools_metadata_url = '',
                use_internal_tools_metadata = True
            )
        else:
            return UpdateGiteaEndpointParams(
        )
        """

    def testUpdateGiteaEndpointParams(self):
        """Test UpdateGiteaEndpointParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
