# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.repositories_api import RepositoriesApi


class TestRepositoriesApi(unittest.TestCase):
    """RepositoriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RepositoriesApi()

    def tearDown(self) -> None:
        pass

    def test_create_repo(self) -> None:
        """Test case for create_repo

        Create repository with the parameters given.
        """
        pass

    def test_create_repo_pool(self) -> None:
        """Test case for create_repo_pool

        Create repository pool with the parameters given.
        """
        pass

    def test_create_repo_scale_set(self) -> None:
        """Test case for create_repo_scale_set

        Create repository scale set with the parameters given.
        """
        pass

    def test_delete_repo(self) -> None:
        """Test case for delete_repo

        Delete repository by ID.
        """
        pass

    def test_delete_repo_pool(self) -> None:
        """Test case for delete_repo_pool

        Delete repository pool by ID.
        """
        pass

    def test_get_repo(self) -> None:
        """Test case for get_repo

        Get repository by ID.
        """
        pass

    def test_get_repo_pool(self) -> None:
        """Test case for get_repo_pool

        Get repository pool by ID.
        """
        pass

    def test_get_repo_webhook_info(self) -> None:
        """Test case for get_repo_webhook_info

        Get information about the GARM installed webhook on a repository.
        """
        pass

    def test_install_repo_webhook(self) -> None:
        """Test case for install_repo_webhook

        """
        pass

    def test_list_repo_instances(self) -> None:
        """Test case for list_repo_instances

        List repository instances.
        """
        pass

    def test_list_repo_pools(self) -> None:
        """Test case for list_repo_pools

        List repository pools.
        """
        pass

    def test_list_repo_scale_sets(self) -> None:
        """Test case for list_repo_scale_sets

        List repository scale sets.
        """
        pass

    def test_list_repos(self) -> None:
        """Test case for list_repos

        List repositories.
        """
        pass

    def test_uninstall_repo_webhook(self) -> None:
        """Test case for uninstall_repo_webhook

        Uninstall organization webhook.
        """
        pass

    def test_update_repo(self) -> None:
        """Test case for update_repo

        Update repository with the parameters given.
        """
        pass

    def test_update_repo_pool(self) -> None:
        """Test case for update_repo_pool

        Update repository pool with the parameters given.
        """
        pass


if __name__ == '__main__':
    unittest.main()
