# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.password_login_params import PasswordLoginParams

class TestPasswordLoginParams(unittest.TestCase):
    """PasswordLoginParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PasswordLoginParams:
        """Test PasswordLoginParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PasswordLoginParams`
        """
        model = PasswordLoginParams()
        if include_optional:
            return PasswordLoginParams(
                password = '',
                username = ''
            )
        else:
            return PasswordLoginParams(
        )
        """

    def testPasswordLoginParams(self):
        """Test PasswordLoginParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
