# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.models.github_pat import GithubPAT

class TestGithubPAT(unittest.TestCase):
    """GithubPAT unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubPAT:
        """Test GithubPAT
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubPAT`
        """
        model = GithubPAT()
        if include_optional:
            return GithubPAT(
                oauth2_token = ''
            )
        else:
            return GithubPAT(
        )
        """

    def testGithubPAT(self):
        """Test GithubPAT"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
