# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.forge_instances_api import ForgeInstancesApi


class TestForgeInstancesApi(unittest.TestCase):
    """ForgeInstancesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ForgeInstancesApi()

    def tearDown(self) -> None:
        pass

    def test_create_forge_instance(self) -> None:
        """Test case for create_forge_instance

        Create forge instance with the given parameters.
        """
        pass

    def test_create_forge_instance_pool(self) -> None:
        """Test case for create_forge_instance_pool

        Create forge instance pool with the parameters given.
        """
        pass

    def test_delete_forge_instance(self) -> None:
        """Test case for delete_forge_instance

        Delete forge instance by ID.
        """
        pass

    def test_delete_forge_instance_pool(self) -> None:
        """Test case for delete_forge_instance_pool

        Delete forge instance pool by ID.
        """
        pass

    def test_get_forge_instance(self) -> None:
        """Test case for get_forge_instance

        Get forge instance by ID.
        """
        pass

    def test_get_forge_instance_pool(self) -> None:
        """Test case for get_forge_instance_pool

        Get forge instance pool by ID.
        """
        pass

    def test_get_forge_instance_webhook_info(self) -> None:
        """Test case for get_forge_instance_webhook_info

        Get information about the GARM installed webhook on a forge instance.
        """
        pass

    def test_install_forge_instance_webhook(self) -> None:
        """Test case for install_forge_instance_webhook

        """
        pass

    def test_list_forge_instance_instances(self) -> None:
        """Test case for list_forge_instance_instances

        List forge instance runner instances.
        """
        pass

    def test_list_forge_instance_pools(self) -> None:
        """Test case for list_forge_instance_pools

        List forge instance pools.
        """
        pass

    def test_list_forge_instances(self) -> None:
        """Test case for list_forge_instances

        List all forge instances.
        """
        pass

    def test_uninstall_forge_instance_webhook(self) -> None:
        """Test case for uninstall_forge_instance_webhook

        Uninstall forge instance webhook.
        """
        pass

    def test_update_forge_instance(self) -> None:
        """Test case for update_forge_instance

        Update forge instance with the given parameters.
        """
        pass

    def test_update_forge_instance_pool(self) -> None:
        """Test case for update_forge_instance_pool

        Update forge instance pool with the parameters given.
        """
        pass


if __name__ == '__main__':
    unittest.main()
