# coding: utf-8

"""
    Garm API.

    The Garm API generated using go-swagger.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from garm_client.api.organizations_api import OrganizationsApi


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_org(self) -> None:
        """Test case for create_org

        Create organization with the parameters given.
        """
        pass

    def test_create_org_pool(self) -> None:
        """Test case for create_org_pool

        Create organization pool with the parameters given.
        """
        pass

    def test_create_org_scale_set(self) -> None:
        """Test case for create_org_scale_set

        Create organization scale set with the parameters given.
        """
        pass

    def test_delete_org(self) -> None:
        """Test case for delete_org

        Delete organization by ID.
        """
        pass

    def test_delete_org_pool(self) -> None:
        """Test case for delete_org_pool

        Delete organization pool by ID.
        """
        pass

    def test_get_org(self) -> None:
        """Test case for get_org

        Get organization by ID.
        """
        pass

    def test_get_org_pool(self) -> None:
        """Test case for get_org_pool

        Get organization pool by ID.
        """
        pass

    def test_get_org_webhook_info(self) -> None:
        """Test case for get_org_webhook_info

        Get information about the GARM installed webhook on an organization.
        """
        pass

    def test_install_org_webhook(self) -> None:
        """Test case for install_org_webhook

        """
        pass

    def test_list_org_instances(self) -> None:
        """Test case for list_org_instances

        List organization instances.
        """
        pass

    def test_list_org_pools(self) -> None:
        """Test case for list_org_pools

        List organization pools.
        """
        pass

    def test_list_org_scale_sets(self) -> None:
        """Test case for list_org_scale_sets

        List organization scale sets.
        """
        pass

    def test_list_orgs(self) -> None:
        """Test case for list_orgs

        List organizations.
        """
        pass

    def test_uninstall_org_webhook(self) -> None:
        """Test case for uninstall_org_webhook

        Uninstall organization webhook.
        """
        pass

    def test_update_org(self) -> None:
        """Test case for update_org

        Update organization with the parameters given.
        """
        pass

    def test_update_org_pool(self) -> None:
        """Test case for update_org_pool

        Update organization pool with the parameters given.
        """
        pass


if __name__ == '__main__':
    unittest.main()
